SELECT DISTINCT T10.*
FROM (SELECT ARRAY[NULL, NULL] AS C1, T1.*, * FROM (SELECT T1.*, NULL, (NULL, NULL) FROM T1, T2, T3, (SELECT * FROM (SELECT *, T4.* FROM (SELECT T3.* FROM T4 LIMIT (- (NULL))) AS T5) AS T6, T7) AS T8) AS T9, T10 LIMIT |/ NULL
) AS T11
